let data
export default data=[
    {
      id:1,
      img:"https://i.ibb.co/7NHbgCS/165355-single-male-elephant-in-the-masai-mara.jpg",
      answer:"Elephant",
      options:[
          "Elephant",
          "Deer",
          "Lion"
      ]
    },
    {
      id:2,
      img:"https://i.ibb.co/pKjf9qS/gettyimages-168504892-1568303467.png",
      answer:"Deer",
      options:[
       "Tiger",
        "Deer",
       "Lion"
      ]
    },
    {
      id:3,
      img:"https://i.ibb.co/TLwxJrL/tiger-medium.jpg",
      answer:"Tiger",
      options:[
           "Tiger",
           "Elephant",
           "Bear",
      ]
    },
    {
      id:4,
      img:"https://i.ibb.co/ZG3WspZ/5a298475d7439-image.jpg",
      answer:"Horse",
      options:[
      "Elephant",
       "Zebra",
      "Horse"
      ]
    },
    {
      id:5,
      img:"https://i.ibb.co/BC57jCn/images-q-tbn-ANd9-Gc-RFBgj-pw6-U1-AVci-P7j-DU9a-KZV6u-Ro-Esl6czw-usqp-CAU.jpg",
      answer:"Zebra",
      options:[
        "Lion",
        "Zebra",
       "Horse"
      ]
    },
    {
      id:6,
      img:"https://i.ibb.co/WFHsTmz/Getty-Images-691120979-1440x1079.jpg",
      answer:"Lion",
      options:[
          "Elephant",
         "Tiger",
          "Lion"
      ]
    },
    {
      id:7,
      img:"https://i.ibb.co/sFQTDgy/a50c90787e781e697be9903455232c47.png",
      answer:"Dog",
      options:[
        "Dog",
       "Deer",
      "Tiger",
       
      ]
    }
  ];
 
  